// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20260620211426_History")]
    partial class History
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex(new[] { "Name" }, "idx_name")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_name");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Weather", b =>
                {
                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<double>("Pressure")
                        .HasColumnType("double precision")
                        .HasColumnName("pressure");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("Water")
                        .HasColumnType("double precision")
                        .HasColumnName("water");

                    b.Property<double>("Wind")
                        .HasColumnType("double precision")
                        .HasColumnName("wind");

                    b.HasKey("CityId")
                        .HasName("pk_weathers");

                    b.ToTable("weathers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WeatherHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_weather_histories");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_weather_histories_city_id");

                    b.ToTable("weather_histories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Weather", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithOne("Weather")
                        .HasForeignKey("Domain.Entities.Weather", "CityId")
                        .HasConstraintName("fk_weathers_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.WeatherHistory", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("History")
                        .HasForeignKey("CityId")
                        .HasConstraintName("fk_weather_histories_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
